# Default values for fiware-dataspace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  consumer:
    domainSuffix: dataconsumer.fr
    namespace: fiware-dsc-consumer01

  provider:
    domainSuffix: dataprovider.fr
    namespace: fiware-dsc-provider01

  trustanchor:
    domainSuffix: trust-anchor.fr
    namespace: trust-anchor
