# Default values for fiware-dataspace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  consumer: fiware-sdc-consumer01

  provider: fiware-sdc-provider01

  trustanchor: trust-anchor
