apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'fiware-dataspace-deployer'
spec:
  project: default
  source:
    repoURL: 'https://github.com/dakountche/dsc.git'
    targetRevision: dev
    path: charts/fiware-dataspace
    helm:
      values: |
        global:
          consumer:
            domainSuffix: dataconsumer.fr
            namespace: fiware-sdc-consumer01

          provider:
            domainSuffix: dataprovider.fr
            namespace: fiware-sdc-provider01

          trust-anchor:
            domainSuffix: trust-anchor.fr
            namespace: trust-anchor
  destination:
      server: 'https://kubernetes.default.svc'
