apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'infra'
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dakountche/dsc.git'
    targetRevision: dev
    path: charts/infra
    helm:

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'infra'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

