apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'fiware-sdc-mongo-operator'
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://mongodb.github.io/helm-charts'
    targetRevision: 0.13.0
    chart: community-operator
    helm:
      values: |
        mongo-operator:
          enabled: true
          database:
            namespace: provider
          operator:
            watchNamespace: "*"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'fiware-mvd-provider01'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

