apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'fiware-dsc-mongo-operator'
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://mongodb.github.io/helm-charts'
    targetRevision: 0.13.0
    chart: community-operator
    helm:
      values: |
        mongo-operator:
          enabled: true
          database:
            namespace: {{ .Values.global.provider.namespace }}
          operator:
            watchNamespace: "*"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.global.provider.namespace }}  
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true

